name: edventure
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  curved_navigation_bar: ^1.0.6
  location: ^6.0.2 
  flutter_typeahead: ^5.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  image_picker: ^1.1.2
  file_picker: ^8.1.3
  socket_io_client: ^3.0.0
  intl: ^0.17.0 
  pinput: ^5.0.0
  timeago: ^3.3.0
  dio: ^5.7.0
  http_parser: ^4.0.2
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

